#Create Custom Container Image
#Push to DockerHub Registry
---
- hosts: localhost
  tasks: 
  - name: Pull .war artifact from Artifactory
    become: true
    get_url:
      url: 
      dest: /home/ec2-user
      url_username: admin
      url_password: Admin123

  - name: Rename .war Artifact
    command: mv sanjoapp-1.0-RELEASE.war sanjoapp.war
  
  - name: Pull Tomcat  Container Image
    docker_image:
      name: tomcat:latest
      source: pull

  - name: Build image and with build args
    docker_image:
      name: 
      build:
        path: /home/ec2-user
        pull: no
        args:
          listen_port: 8080
      source: build

  - name: Log into DockerHub
    docker_login:
     username: 
     password: 

    
  - name: Push to docker hub
    docker_image:
      name: 
      repository: 
      push: yes
      source: local
