#Service Type nodePort
apiVersion: v1
kind: Service
metadata:
  name: sanjo-service
  labels:
    app: sanjo-app
spec:
  selector:
    app: sanjo-app

  type: NodePort
  ports:
  - nodePort: 31000
    port: 8080
    targetPort: 8080
